CREATE TABLE quotes (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    quote_number VARCHAR(30) NOT NULL,
    title VARCHAR(180) NOT NULL,
    template_key VARCHAR(40) NOT NULL DEFAULT 'modern',
    status ENUM('draft', 'sent', 'viewed', 'accepted', 'rejected', 'canceled') NOT NULL DEFAULT 'draft',
    discount_total DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    shipping_total DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    subtotal_total DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    total DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    validity_days INT UNSIGNED NOT NULL DEFAULT 7,
    payment_terms VARCHAR(255) NULL,
    warranty VARCHAR(255) NULL,
    notes TEXT NULL,
    sent_at DATETIME NULL,
    viewed_at DATETIME NULL,
    accepted_at DATETIME NULL,
    rejected_at DATETIME NULL,
    canceled_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_quotes_company_number (company_id, quote_number),
    INDEX idx_quotes_company_id (company_id),
    INDEX idx_quotes_client_id (client_id),
    INDEX idx_quotes_status (status),
    INDEX idx_quotes_created_at (created_at),
    CONSTRAINT fk_quotes_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_quotes_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE quote_items (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    quote_id BIGINT UNSIGNED NOT NULL,
    item_type ENUM('service', 'product', 'custom') NOT NULL DEFAULT 'custom',
    item_ref_id BIGINT UNSIGNED NULL,
    description VARCHAR(255) NOT NULL,
    quantity DECIMAL(15,2) NOT NULL DEFAULT 1.00,
    unit_label VARCHAR(40) NOT NULL DEFAULT 'un',
    unit_price DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    discount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    total DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    sort_order INT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_quote_items_quote_id (quote_id),
    INDEX idx_quote_items_type (item_type),
    CONSTRAINT fk_quote_items_quote FOREIGN KEY (quote_id) REFERENCES quotes(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
