CREATE TABLE contracts (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    quote_id BIGINT UNSIGNED NULL,
    contract_number VARCHAR(30) NOT NULL,
    title VARCHAR(180) NOT NULL,
    status ENUM('draft', 'sent', 'signed', 'active', 'completed', 'canceled') NOT NULL DEFAULT 'draft',
    starts_at DATE NULL,
    ends_at DATE NULL,
    value_total DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    payment_terms VARCHAR(255) NULL,
    scope TEXT NULL,
    terms TEXT NULL,
    notes TEXT NULL,
    signed_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_contracts_company_number (company_id, contract_number),
    INDEX idx_contracts_company_id (company_id),
    INDEX idx_contracts_client_id (client_id),
    INDEX idx_contracts_quote_id (quote_id),
    INDEX idx_contracts_status (status),
    INDEX idx_contracts_starts_at (starts_at),
    CONSTRAINT fk_contracts_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_contracts_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE RESTRICT,
    CONSTRAINT fk_contracts_quote FOREIGN KEY (quote_id) REFERENCES quotes(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
